gallery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from gallery import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pictures/', include('pictures.urls')),
    path('', RedirectView.as_view(url='pictures/'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pictures/urls.py
from django.urls import path
from pictures.views import landing_page, PictureCreateView, CategoryCreateView

app_name = 'pictures'

urlpatterns = [
    path('', landing_page, name='pictures-landing-page'),
    path('create/', PictureCreateView.as_view(), name='picture-create'),
    path('category-create/', CategoryCreateView.as_view(), name='category-create')
]

pictures/models.py
from django.db import models
import uuid
from datetime import date
# Create your models here.


class Category(models.Model):
    category = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.category


def unique_file_name(instance, filename):
    file_ext = filename.split('.')[-1]
    return f'{date.today()}/{uuid.uuid4()}.{file_ext}'


class Picture(models.Model):
    title = models.CharField(max_length=50)
    picture = models.ImageField(upload_to=unique_file_name)
    category = models.ForeignKey(
        'Category', on_delete=models.SET_NULL, null=True, blank=True)
    description = models.TextField(max_length=500, null=True, blank=True)

    def __str__(self):
        return f"{self.title}:{self.picture.name}"

pictures/forms.py
from django.forms import ModelForm
from pictures.models import Picture, Category


class PictureForm(ModelForm):
    class Meta():
        model = Picture
        fields = ['title', 'picture', 'category', 'description']

    def __init__(self, *args, **kwargs):
        super(PictureForm, self).__init__(*args, **kwargs)
        for f in self.fields:
            self.fields[f].widget.attrs.update({'class': 'form-control'})
        
        self.fields['category'].widget.attrs.update({'class': 'form-select'})
        self.fields['description'].widget.attrs.update({'style': 'height: 200px'})


class CategoryForm(ModelForm):
    class Meta():
        model = Category
        fields = ['category']

    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        for f in self.fields:
            self.fields[f].widget.attrs.update({'class': 'form-control'})

pictures/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from pictures.models import Category, Picture
from pictures.forms import PictureForm, CategoryForm
from django.urls import reverse_lazy

# Create your views here.


def landing_page(request):
    categories = Category.objects.all()

    req_category = request.GET.get('category')
    if (req_category is not None):
        pictures = Picture.objects.all().filter(category__category=req_category)
        message = "Result: category = {}, {} pictures".format(
            req_category, pictures.count())
    else:
        pictures = Picture.objects.all()
        message = "Result: category = all categories, {} pictures".format(
            pictures.count())

    ctx = {
        'categories': categories,
        'pictures': pictures,
        'message': message
    }
    return render(request, 'pictures/index.html', context=ctx)


class PictureCreateView(CreateView):
    form_class = PictureForm
    model = Picture
    success_url = reverse_lazy('pictures:pictures-landing-page')
    # looks for modelname_form.html -> picture_form.html


class CategoryCreateView(CreateView):
    form_class = CategoryForm
    success_url = reverse_lazy('pictures:pictures-landing-page')
    template_name = 'pictures/category-form.html'

    def form_invalid(self, form):
        print("Form is invalid")
        return super().form_invalid(form)

pictures/templates/pictures/category-form.html
{% extends "base_generic.html" %}

{% block content %}

    <div class="container shadow p-3 bg-body rounded mt-4" style="max-width:500px">
        <h3> Create a category </h3>
        <hr>
        <form action="" method="post" class="mt-3">
            {% csrf_token %}
            
            {% for f in form %}
                <div class="mb-3">
                    <label class="mb-1 form-label">{{ f.label }} </label>
                    {{f}}
                    <p class="text-danger ms-2" style=" font-size:13px">{{ f.errors|striptags }}</p>
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary mb-3">Create</button>
        </form>
    </div>

{% endblock %}

pictures/templates/pictures/index.html
{% extends "base_generic.html" %}

{% block content %}
{% load static %}
<div class="outer-grid-container">
    <div class="" style="height:100%">
        <ul class="list-group">
            <li class="list-group-item list-group-item-dark">Categories</li>
            <a href="/pictures/" class="list-group-item list-group-item-action">All</a>

            {% for c in categories %}
            <a href="/pictures/?category={{ c.category }}" class="list-group-item list-group-item-action">{{c.category}}</a>
            {% endfor %}
            <a href="{% url 'pictures:category-create' %}" class="list-group-item-action btn btn-primary list-group-custom">
                + Add Category
            </a>
            <a href="{% url 'pictures:picture-create' %}" class="list-group-item-action btn btn-primary list-group-custom">
                + Add Picture
            </a>
          </ul>
    </div>
    <div>
        <h6 class="ps-4 pt-2"> {{message}} </h6>
        <div class="flex-container p-4">
            {% for p in pictures %}
                <div class="card custom-card p-3 m-2" style="width: 25rem;">
                    <div>
                        <img src="{{p.picture.url}}" class="card-img-top" alt="...">
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{p.title}}</h5>
                        <span class="badge text-bg-secondary">{{p.category.category}}</span>
                        <p class="card-text">{{p.description}}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

pictures/templates/pictures/picture_form.html
{% extends "base_generic.html" %}

{% block content %}

    <div class="container shadow p-3 bg-body rounded mt-4" style="max-width:500px">
        <h3> Add a picture </h3>
        <hr>
        <form action="" method="post" class="mt-3" enctype="multipart/form-data">
            {% csrf_token %}
            
            {% for f in form %}
                <div class="mb-3">
                    <label class="mb-1 form-label">{{ f.label }} </label>
                    {{f}}
                    <p class="text-danger ms-2 lh-1">{{ f.errors|striptags }}</p>
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary mb-3">Create</button>
        </form>
    </div>

{% endblock %}

templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Moments</title>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>

    
    {% block css %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/pictures/stylesheet.css' %}">
    {% endblock %}
</head>
<body>
    <nav class="navbar bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">
            <img src="{% static 'icons/gallery.png' %}" alt="Logo" width="30" height="30" class="d-inline-block align-text-top">
            <h3 class="text-light ps-3 mt-1" style="display:inline">Moments</h3>
          </a>
        </div>
      </nav>

    {% block content %}

    {% endblock %}
</body>
</html>